//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOCK
    {
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.TimeSpan> PlannedStartTime { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.TimeSpan> PlannedEndTime { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.TimeSpan> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.TimeSpan> ActualEndTime { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public System.Guid ID { get; set; }
    }
}
