//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBTYPE
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public string SkillRequired { get; set; }
        public Nullable<int> WorkersRequired { get; set; }
        public string Tools { get; set; }
        public Nullable<decimal> ToolCost { get; set; }
        public string FacilitiesRequired { get; set; }
        public Nullable<decimal> FacilitiesCost { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string Description { get; set; }
        public string AccountCode { get; set; }
        public Nullable<decimal> JobPrice { get; set; }
    }
}
