//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public System.Guid ID { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> Payment1 { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public string Reference { get; set; }
        public string PaymentType { get; set; }
        public string CollectedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.Guid> PaymentTypeID { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
    }
}
