//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOOL()
        {
            this.JOBs = new HashSet<JOB>();
        }
    
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Unit { get; set; }
        public int ID { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public Nullable<System.Guid> GUIDID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB> JOBs { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
