USE [master]
GO

/****** Object:  Database [AuthenticationDB]    Script Date: 16/06/2018 00:36:04 ******/
CREATE DATABASE [AuthenticationDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AuthenticationDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\AuthenticationDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AuthenticationDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\AuthenticationDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AuthenticationDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AuthenticationDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AuthenticationDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AuthenticationDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AuthenticationDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AuthenticationDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AuthenticationDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AuthenticationDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AuthenticationDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AuthenticationDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AuthenticationDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AuthenticationDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AuthenticationDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AuthenticationDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AuthenticationDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AuthenticationDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AuthenticationDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AuthenticationDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AuthenticationDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AuthenticationDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AuthenticationDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AuthenticationDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AuthenticationDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AuthenticationDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AuthenticationDB] SET RECOVERY FULL 
GO

ALTER DATABASE [AuthenticationDB] SET  MULTI_USER 
GO

ALTER DATABASE [AuthenticationDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AuthenticationDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AuthenticationDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AuthenticationDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AuthenticationDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AuthenticationDB] SET QUERY_STORE = OFF
GO

USE [AuthenticationDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AuthenticationDB] SET  READ_WRITE 
GO

